kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: patrickstigler/tidal-dl-docker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest